### ISSUE TITLE
CounterAuthenticator ignores counter

### ISSUE THREAD

**Issue by whatsdis** [glacasa/TwoStepsAuthenticator#11]
it seems to completely ignore the counter, for example I pass in a zero constantly and it works every time. Shouldn't the number generated on Google Authenticator not work after the first time it's accepted because the server is always set to zero?

Or do I need to implement the isUsed() method? Do you have an example of this?

**Comment by glacasa** [comment]
The IsUsed method is only implemented on the TimeAuthenticator (I will update the readme to clarify this point).

On this version, the CounterAuthenticator doesn't keep track of the used codes. 
There's a problem because the used codes and current count need to be saved somewhere, and can't be kept in memory like in the time authenticator, so we can't create a default working UsedCodeManager.

If you need to use  the counter authenticator, you need to keep track of the counter and the used codes by yourself. I will see if I can add a UsedCodeManager in the CounterAuthenticator for the next release.

**Comment by whatsdis** [comment]
wow, thanks for such a fast response!

got it, so store it on a database somewhere? whereabouts in the code would I perform the check to see if the counter is synchronized, I guess UsedCodeManager.cs ? so if counter is not synchronized, reject the code. if a code is used once, then upon `.checkcode()` we see if this has already been used and reject in such case? so I guess I need to setup a database schema that stores used numbers and counter, man this is so much extra work involved than I anticipated :/

hmmm I guess I better use TimeAuthenticator for now seems like more work is involved with counter authenticator. I was worried that there would be time drift (mobile phone runs out of battery etc) which is why I chose CounterAuthenticator. What is the threshold for such events and how does this library handle those edge cases?

when can we expect the next release? I think it might be hard without some persistence baked in.

**Comment by glacasa** [comment]
Ok, I was writing a very long message to explain what to do, and I understood that I missed a very important thing about CodeAuthenticator (I'm not the one who wrote it, I'm the TimeAuth guy)

Here is how it works :

When you call the CheckCode, you send the position of the currentCounter (last counter used + 1). So if you call this method again, you send a different counter position, so the previously used codes can't be validated.

So, what you have to do is, for every user, to save the position of the last counter used - only the codes after the last one are allowed.

When you call this method :
`CheckCode(string secret, string code, ulong counter, out ulong usedCounter)`

`ulong counter`is the counter position of the first code allowed
`out ulong usedCounter`is -if the code is valid- the counter position of the code used. Just save this code to your database, 

The next time you call CheckCode, the value for `counter` must be the last counter + 1

**Comment by glacasa** [comment]
I won't make a new release for this, but the README definitely needs an update. I will do it in the next few days

**Comment by whatsdis** [comment]
I see, but the TimeAuthenticator does not need any persistent per user right?

What about other libraries out there, do any exist that do not need persistence to store used codes or counters per user?

**Comment by glacasa** [comment]
TimeAuthenticator doesn't need persistent storage because codes are generated using the current time ; so codes are automatically disabled after five minutes by nature - that's why used codes can be kept in memory for this time.

Counter Authenticator needs to keep track of the last code used, because a code can be used at any time, and can be used several days away.

I don't know how other libraries handle this, but I don't see how I can improve this library on this point. 

I could create an ICounterPosition interface (like the IUsedCodeManager), but I'm pretty sure it would make your code more complex : you'd still need to store this information yourself.

If you have any idea how I could help, let me know.

**Comment by whatsdis** [comment]
Got it. I guess I will have to use TimeAuthenticator. I'm just worried about time sync drifting
